### ISSUE TITLE
Speaker Poster : Rust-Hacks-at-Cummins

### ISSUE THREAD

**Issue by nomadicmehul** [rusthacks/OpenDesign#2]
## Goal: 
Speaker Poster for Rust-Hacks-at-Cummins

## Info: 
Rust Programming workshop at Cummins College of Engineering for Women. It's for social media and blog post. 

More details : https://github.com/rowdymehul/Rust-Hacks-at-Cummins

## Style Information: 
Code theme as its a workshop and use Rust design. 

## Deadline: 
12th Match'18

## Tag: 
Design Needed

**Comment by pransh15** [comment]
@rowdymehul, since you're the speaker, can you share the picture you'd want to share in the poster.

**Comment by nomadicmehul** [comment]
Hi @pransh15,  sharing drive link which had some pictures, you can use the best according to design.  https://drive.google.com/open?id=0B_FL7bWCWf8gaXNvaFZXWWNFUzA

**Comment by pransh15** [comment]
![rustatcummins_speaker](https://user-images.githubusercontent.com/18158596/37092320-70dc5b10-2231-11e8-8364-28eb163dc0f4.jpg)

Some great pictures there, mate. Here is a poster to share. Take a look! :)

**Comment by pransh15** [comment]
![rustatcummins_speaker](https://user-images.githubusercontent.com/18158596/37092786-1c5bc6f0-2233-11e8-9ede-b19ff0e96081.jpg)

Updated the title.

**Comment by nomadicmehul** [comment]
Looks great Brother, but can we have any other option for background color? Speaker photo looks very bright in color so. Rest, over to you.

**Comment by pransh15** [comment]
![rustatcummins_speaker](https://user-images.githubusercontent.com/18158596/37114960-cf503a2a-226f-11e8-8faa-e458787080d5.jpg)

A brighter color option in the same color scheme. :D

**Comment by nomadicmehul** [comment]
Looks good! :) So this is the final one?

**Comment by pransh15** [comment]
Since this is done, closing this! :)
